[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"


[[redirects]]
  from = "/api/catalog"
  to = "/.netlify/functions/catalog"
  status = 200

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/api/teach-plan"
  to = "/.netlify/functions/teach-plan"
  status = 200

[[redirects]]
  from = "/api/esv-passages"
  to = "/.netlify/functions/esv-passages"
  status = 200

[[redirects]]
  from = "/api/key"
  to = "/.netlify/functions/api-key"
  status = 200
